// Code generated by mockery v2.10.0. DO NOT EDIT.

package optimism

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	rosetta_sdk_gotypes "github.com/coinbase/rosetta-sdk-go/types"

	types "github.com/ethereum-optimism/optimism/l2geth/core/types"
)

// CurrencyFetcher is an autogenerated mock type for the CurrencyFetcher type
type CurrencyFetcher struct {
	mock.Mock
}

// fetchCurrency provides a mock function with given fields: ctx, block, contractAddress
func (_m *CurrencyFetcher) fetchCurrency(ctx context.Context, block *types.Block, contractAddress string) (*rosetta_sdk_gotypes.Currency, error) {
	ret := _m.Called(ctx, block, contractAddress)

	var r0 *rosetta_sdk_gotypes.Currency
	if rf, ok := ret.Get(0).(func(context.Context, *types.Block, string) *rosetta_sdk_gotypes.Currency); ok {
		r0 = rf(ctx, block, contractAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rosetta_sdk_gotypes.Currency)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *types.Block, string) error); ok {
		r1 = rf(ctx, block, contractAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
